version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - api
  api:
    build: ./docker/api
    volumes:
      - .:/var/www/collective-times/api
    depends_on:
      - database
  database:
    image: postgres:12
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'collective_times_development'
      POSTGRES_PASSWORD: 'collective_times'
      POSTGRES_DB: 'collective_times_development'
  cache:
    image: redis:4

