apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: php-fpm
spec:
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  labels:
    app: "nginx"
spec:
  containers:
    - name: nginx
      image: "api-nginx"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: "php-fpm"
  labels:
    app: "php-fpm"
spec:
  containers:
    - name: php-fpm
      image: "api-php-fpm"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9000
